server:
  port: 8081

spring:
  config:
    activate:
      on-profile: prod

  # postgres db setting
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_tutorial
    username: postgres
    password: 1234
    show-sql: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        format_sql: false
        show_sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: false
